/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    403: typeof import('./src/components/errpage/403.vue')['default']
    404: typeof import('./src/components/errpage/404.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    Errpage: typeof import('./src/components/errpage/index.vue')['default']
    Header: typeof import('./src/components/layout/header.vue')['default']
    Icon: typeof import('./src/components/global/icon/index.vue')['default']
    MenuTree: typeof import('./src/components/layout/menu-tree.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/layout/sidebar.vue')['default']
  }
}
